---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/posts":
    get:
      summary: Lista todos os posts
      tags:
      - Posts
      responses:
        '200':
          description: sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    title:
                      type: string
                    body:
                      type: string
                    created_at:
                      type: string
                      format: date-time
                    updated_at:
                      type: string
                      format: date-time
                  required:
                  - id
                  - title
                  - body
    post:
      summary: Cria um post
      tags:
      - Posts
      parameters: []
      responses:
        '422':
          description: parâmetros inválidos
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                body:
                  type: string
              required:
              - title
              - body
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
