default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DB_USERNAME", "postgres") %>
  password: <%= ENV.fetch("DB_PASSWORD", "password") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>//

development:
  <<: *default
  database: app_development

test:
  <<: *default
  database: app_test
  host: db
  user: <%= ENV.fetch("DB_USERNAME", "postgres") %>
  password: <%= ENV.fetch("DB_PASSWORD", "password") %>

production:
  <<: *default
  database: app_production
  username: app
  password: <%= ENV.fetch("DB_PASSWORD", "password") %>
